#! /usr/bin/env bash

OSX_CMD='/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport'


if which ${OSX_CMD} > /dev/null 2>&1; then
  ${OSX_CMD} -s
else
  echo I\'ve got no idea what\'s going on
  exit 1
fi
